### ISSUE TITLE
Texture plugin never runs in OJS 3.1.1

### ISSUE THREAD

**Issue by abdulsamad544** [asmecher/texture#10]
I have an OJS running with texture plugin installed. But this plugin doesn't shows up anywhere in the workflow. I have tested many times even on a fresh install of OJS on other hosting and local servers because error log reports depreciation warning.

[30-Oct-2018 10:59:58 UTC] PHP Strict Standards:  Declaration of TexturePlugin::register() should be compatible with LazyLoadPlugin::register($category, $path, $mainContextId = NULL) in /home/roesolca/public_html/plugins/generic/texture/TexturePlugin.inc.php on line 141

Is there any way we can disable Lazyload plugin if this is the major error causing reason.

Please tell if there is a way to resolve this error along with multiple other depreciation warnings. If there is a problem with PHP version do tell me. I am running 5.6 Native PHP. 

By default OJS doesn't runs many of the plugins like texture, JATS template etc due to these warnings. Please help me resolve these issues since I am fed up of this.

**Comment by asmecher** [comment]
@abdulsamad544, please be respectful.

How did you install the plugin? Through the plugin gallery, or by unpacking the `.tar.gz` manually, or some other means?

OJS currently produces strict standard and deprecation warnings, which we are working gradually to resolve, and which stem from recent releases of PHP being more stringent about calling conventions. If you direct these warnings to your PHP error log rather than the browser, they won't interfere. This is recommended generally for production use of PHP.

**Comment by abdulsamad544** [comment]
Not being disrespectful at all.
Yes I have installed the plugin through plugin gallery from dashboard.

**Comment by abdulsamad544** [comment]
Would be very thankful to you if you can help me overcome this issue. And appreciate you cooperation, I know you have already helped a lot others. Thanks

**Comment by asmecher** [comment]
If you've already installed via the plugin gallery, it's likely that just adjusting the way PHP handles error messages will resolve the problems you've been having.

**Comment by abdulsamad544** [comment]
Ok, please help me by elaborating a little, how will I change that handling. I guess you are talking to direct these error warnings to PHP error log. I actually picked up the depreciation warning stated above from error_log file from public_html folder. Something to change in php.ini?

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by asmecher** [comment]
@abdulsamad544, you mentioned earlier that warning messages were interfering with the site, so I assumed they were being directed to the browser. If that's not the case, then you can ignore those warnings (strict mode and deprecation).

Have you tried uploading an XML file to one of the workflow areas?

**Comment by abdulsamad544** [comment]
Yes, interfering in the sense that plugins dont work which are showing strict warnings. But no errors are reported in the browser console. I may ignore these errors if they aren't causing plugins to stop working. But these also flood error log file.
Yes I have uploaded XML files exported from Native XML export plugin but those aren't validated and the loading article loader runs forever. I tried uploading an XML from elife lens viewer demo source and it ran. The major problem here is that we want to generate an XML for our articles which runs in OJS. But finding a good JATS XML editor is difficult. Texture might be the right option but isn't working.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by asmecher** [comment]
The native XML is a different schema than JATS, so the Texture plugin and Lens Reader plugin (which only work on JATS) won't work with XML that comes from that source.

The Texture plugin is intended for editing existing XML, not creating new XML, so you'll have to create your initial XML from another source. See for example https://pkp.sfu.ca/open-typesetting-stack/.

If you have more questions about this, I'd suggest starting a topic over in the support forum (http://forum.pkp.sfu.ca/). That's a good place for general discussion; this is intended for specific bugs or new feature development.
